#!/bin/bash

set -e

case "$1" in
    configure)
        LOGDIR="/var/log/atop"
        if [ ! -d "/run/systemd/system" ];then
            touch $LOGDIR/dummy_after $LOGDIR/dummy_before
        fi
        if [ -d "/run/pacct_shadow.d" ];then
            rm -rf /run/pacct_shadow.d
            rm -f /run/pacct_source
        fi
        DATE="$(date +%Y%m%d)"
        # check whether atop will read its own latest file
        # point atop to the latest file and check for output on stdout
        # the pipe will prevent atop from going interactive, and if it
        # won't read the file, stdout will be empty.
        if ls -t $LOGDIR/atop_${DATE} > /dev/null 2>&1; then
            LATESTFILE="/var/log/atop/atop_${DATE}"
            if ! atop -r $LATESTFILE 2>/dev/null | head -n 5 | grep -q '.'; then
                mv "/var/log/atop/atop_${DATE}" "/var/log/atop/atop_${DATE}_old"
            fi
        fi
    ;;
esac

# Not sure which debhelper version is used when building atop, manually enable
# atop/atopacct/atop-rotate.
# 1. atop.service
if deb-systemd-helper --quiet was-enabled 'atop.service'; then
    deb-systemd-helper enable 'atop.service' > /dev/null || true
else
    deb-systemd-helper update-state 'atop.service' >/dev/null || true
fi
# 2. atopacct.service
if deb-systemd-helper --quiet was-enabled 'atopacct.service'; then
    deb-systemd-helper enable 'atopacct.service' > /dev/null || true
else
    deb-systemd-helper update-state 'atopacct.service' >/dev/null || true
fi
# 3. atop-rotate.timer
if deb-systemd-helper --quiet was-enabled 'atop-rotate.timer'; then
    deb-systemd-helper enable 'atop-rotate.timer' > /dev/null || true
else
    deb-systemd-helper update-state 'atop-rotate.timer' >/dev/null || true
fi

# Forced umask and restart atop-rotate.timer, instead of try-restart,
# man systemctl for more details
deb-systemd-helper unmask atop-rotate.timer >/dev/null || true

if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
                _dh_action=restart
        else
                _dh_action=start
        fi
        deb-systemd-invoke $_dh_action atop-rotate.timer >/dev/null || true
fi

#DEBHELPER#

# vim: tabstop=4 expandtab

