name: release
on: [push] # 仓库提交时触发
jobs:
  job1: # 发布任务
    runs-on: ubuntu-latest # 运行系统环境
    steps: # 步骤
      - name: build
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
        id: step_one
      - name: install
        id: step_two
        run: |
          ls
          pwd
          git branch
          if atop -V ; then echo "assert: atop have installed "; exit;fi
          sudo make && sudo make install
          echo '安装完成'
          systemctl status atop.service 
          systemctl status atopacct.service
          systemctl status atop-rotate.timer
          systemctl cat atop.service
          systemctl cat atopacct.service
          systemctl cat atop-rotate.timer
          sudo systemctl stop atop.service 
          systemctl status atop.service 
          sudo systemctl restart atop.service 
          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit;fi
          if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit;fi
      - name: shadowfile_check
        id: step_three
        run: |
          if [ ! -d /run/pacct_shadow.d/ ]; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit -1;fi
          if test -z "$(sudo ls -l /proc/$(pidof atopacctd)/fd|grep pacct_shadow|grep '.paf')"; then echo "assert: atopacctd.paf_check error "; exit -2;fi
          if test -z "$(sudo ls -l /proc/$(pidof atop)/fd|grep pacct_shadow|grep '.paf')"; then echo "assert: atop.paf_check error "; exit -3;fi
      - name: logfile_check
        id: step_four
        run: |
          ls -l /var/log/atop/
          if [ ! -d "/var/log/atop/" ]; then echo "assert: logfile_check_/var/log/atop error" ; exit -1;fi      
          if test -z "$(ls -l /var/log/atop/)"; then echo "assert: logfile_check error/var/log/atop/atop_$(date +%Y%m%d) "; exit -2; fi 
          
