name: release
on: [push] # 仓库提交时触发
jobs:
  job1: # 发布任务
    runs-on: ubuntu-latest # 运行系统环境
    steps: # 步骤
      - name: build
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
        id: step_one
      - name: install
        id: step_two
        run: |
          ls
          pwd
          git branch
          if atop -V ; then echo "assert: atop have installed "; exit;fi
          sudo make && sudo make install
          echo '安装完成'
      - name: test
        id: step_three
        run: |
          systemctl status atop.service 
          systemctl status atopacct.service
          systemctl status atop-rotate.timer
          systemctl cat atop.service
          systemctl cat atopacct.service
          systemctl cat atop-rotate.timer
          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit -1;fi
          if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit -2;fi
      - name: shadowfile_check
        id: step_four
        run: |
          if [ ! -d /run/pacct_shadow.d/ ]; then echo "assert: shadowfile_check error "; exit -1;fi
          if test -z "$(sudo ls -l /proc/$(pidof atopacctd)/fd|grep pacct_shadow|grep '.paf')"; then echo "assert: atopacctd.paf_check error "; exit -2;fi
          if test -z "$(sudo ls -l /proc/$(pidof atop)/fd|grep pacct_shadow|grep '.paf')"; then echo "assert: atop.paf_check error "; exit -3;fi
          sudo systemctl stop atopacct.service && sudo systemctl restart atop && sleep 10
          sudo systemctl restart atopacct
          sudo ls -l /var/cache/atop.d/atop.acct
          if test -z "$(sudo ls -l /var/cache/atop.d/atop.acct)"; then echo "assert: /var/cache/atop.d/atop.acct_check error "; exit -3;fi
      - name: logfile_check
        id: step_five
        run: |
          ls -l /var/log/atop/
          if [ ! -d "/var/log/atop/" ]; then echo "assert: logfile_check_/var/log/atop error" ; exit -1;fi      
          if test -z "$(ls -l /var/log/atop/)"; then echo "assert: logfile_check error/var/log/atop/atop_$(date +%Y%m%d) "; exit -2; fi
      - name: performance
        run: | 
          pwd
          if [ `echo "$(ps aux | grep /usr/bin/atop | head -n 1 | awk '{print($3);}') > 5" |bc` -eq 1 ]; then echo "atop cpu > 5%"; exit -1;fi
          if [ `echo "$(ps aux | grep /usr/bin/atop | head -n 1 | awk '{print($4);}') > 5" |bc` -eq 1 ]; then echo "atop mem > 5%"; exit -1;fi
      - name: memleak
        run: |  
          sudo apt-get install valgrind
          echo $(sudo valgrind --tool=memcheck  --leak-check=full --log-file=temp_valgrind.log /usr/bin/atop) > atop.log &
          echo "sleep start"
          sleep 20
          echo "sleep done"
          ps -aux |grep "valgrind"
          ps -aux |grep "valgrind"| awk '{print $2}' | head -n 1
          sudo kill $(ps -aux |grep "valgrind"| awk '{print $2}' | head -n 1)
          sleep 10
          ps -aux |grep "valgrind"
          cat temp_valgrind.log
          grep --color=auto -rns "definitely lost: 0 bytes in 0 blocks" temp_valgrind.log
          grep --color=auto -rns "indirectly lost: 0 bytes in 0 blocks" temp_valgrind.log
          grep --color=auto -rns "possibly lost: 0 bytes in 0 blocks" temp_valgrind.log
